# docker-compose.yml
version: '3.8' # Specify the Docker Compose file format version

services:
  streamlit-app:
    # Build the image using the Dockerfile in the current directory
    build:
      context: . # Look for the Dockerfile in the current directory
      dockerfile: Dockerfile # Specify the Dockerfile name

    # Map port 8501 on the host to port 8501 in the container
    # Streamlit runs on port 8501 by default
    ports:
      - "8501:8501"

    # Mount the current directory into the container's /app directory.
    # This is useful for development as code changes on your host machine
    # will instantly reflect inside the container without needing to rebuild
    # the image.
    volumes:
      - .:/app

    # --- CORRECTED PART HERE ---
    # Set environment variables for the container.
    # This must be a mapping (dictionary), not a list.
    # Docker Compose will automatically load variables from a .env file
    # in the same directory as this docker-compose.yml file.
    environment:
      GEMINI_API_KEY: "${GEMINI_API_KEY}" # <-- NO HYPHEN HERE, it's a key-value pair
      # Add other environment variables here if needed
      # ANOTHER_VAR: "another_value"

    # Command to run when the container starts.
    # This overrides the ENTRYPOINT in the Dockerfile if you uncomment it.
    # Given your Dockerfile already has the correct ENTRYPOINT, you can keep this commented.
    # command: ["streamlit", "run", "interphase.py", "--server.port", "8501", "--server.address", "0.0.0.0"]